version: '3.4'

services:
  week6task:
    image: week6task
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
